from __future__ import annotations

from typing import Protocol

from app.domain.disclosure_audit_record import DisclosureAuditRecord
from app.domain.provider_application import ProviderOnboardingApplication
from app.domain.provider_attribution_record import ProviderAttributionRecord
from app.domain.provider_trust import ProviderTrustDecision
from app.schemas.checkpoint_gossip import CheckpointGossipPackage
from app.schemas.federation_bundle import FederationBundle
from app.schemas.trust_attestation import TrustDecisionAttestation
from app.schemas.witness_statement import WitnessStatement


class ProviderApplicationRepositoryContract(Protocol):
    def add(self, application: ProviderOnboardingApplication) -> None: ...
    def get(self, application_id: str) -> ProviderOnboardingApplication: ...
    def list_all(self) -> list[ProviderOnboardingApplication]: ...
    def active_for_provider(
        self, provider_id: str
    ) -> ProviderOnboardingApplication | None: ...


class TrustRegistryRepositoryContract(Protocol):
    def add(self, decision: ProviderTrustDecision) -> None: ...
    def list_all(self) -> list[ProviderTrustDecision]: ...
    def latest_for_provider(self, provider_id: str) -> ProviderTrustDecision | None: ...


class TrustAttestationRepositoryContract(Protocol):
    def add(self, attestation: TrustDecisionAttestation) -> None: ...
    def get_by_decision(self, decision_id: str) -> TrustDecisionAttestation | None: ...
    def list_all(self) -> list[TrustDecisionAttestation]: ...


class FederationBundleRepositoryContract(Protocol):
    def add_verified(self, bundle: FederationBundle) -> None: ...
    def list_all(self) -> list[FederationBundle]: ...
    def latest_for_authority(self, authority_id: str) -> FederationBundle | None: ...


class TransparencyLogRepositoryContract(Protocol):
    @property
    def entry_count(self) -> int: ...
    def append(self, entry, persist: bool = True) -> int: ...
    def list_entries(self) -> list: ...
    def current_root(self) -> str: ...
    def latest_tree_head(self): ...


class WitnessStatementRepositoryContract(Protocol):
    def add(self, statement: WitnessStatement, persist: bool = True) -> None: ...
    def list_all(self) -> list[WitnessStatement]: ...


class CheckpointGossipRepositoryContract(Protocol):
    def add(self, package: CheckpointGossipPackage, persist: bool = True) -> None: ...
    def list_all(self, limit: int = 100) -> list[CheckpointGossipPackage]: ...


class AttributionRepositoryContract(Protocol):
    def add(self, record: ProviderAttributionRecord) -> None: ...
    def get(self, generation_id: str) -> ProviderAttributionRecord: ...


class DisclosureAuditRepositoryContract(Protocol):
    def append(self, record: DisclosureAuditRecord) -> None: ...
    def list_all(self) -> list[DisclosureAuditRecord]: ...
